server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Intenta servir el archivo solicitado ($uri), si no existe,
        # intenta como directorio ($uri/), y si tampoco existe,
        # redirige al index.html (necesario para el routing de Angular).
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Configuración para manejar errores
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
